module.exports = [
  {
    key: 'aav2020',
    'x-originalName': 'AAV2020',
    type: 'string',
    title: 'Zonage en aire d\'attraction des villes 2020 d\'implantation de l\'équipement',
    label: 'Zonage en aire d\'attraction des villes 2020 d\'implantation de l\'équipement'
  },
  {
    key: 'an',
    'x-originalName': 'AN',
    type: 'integer',
    title: 'Millésime de la base',
    label: 'Millésime de la base'
  },
  {
    key: 'bv2012',
    'x-originalName': 'BV2012',
    type: 'integer',
    title: 'Bassin de vie 2012 d\'implantation de l\'équipement',
    label: 'Bassin de vie 2012 d\'implantation de l\'équipement'
  },
  {
    key: 'dep',
    'x-originalName': 'DEP',
    type: 'string',
    'x-refersTo': 'http://rdf.insee.fr/def/geo#codeDepartement',
    title: 'Département d\'implantation de l\'équipement',
    label: 'Département d\'implantation de l\'équipement'
  },
  {
    key: 'depcom',
    'x-originalName': 'DEPCOM',
    type: 'string',
    'x-refersTo': 'http://rdf.insee.fr/def/geo#codeCommune',
    'x-capabilities': {
      textAgg: true
    },
    title: 'Code département et commune d\'implantation de l\'équipement',
    label: 'Code département et commune d\'implantation de l\'équipement'
  },
  {
    key: 'dom',
    'x-originalName': 'DOM',
    type: 'string',
    title: 'Domaine d\'appartenance de l\'équipement',
    'x-labels': {
      A: 'Services aux particuliers',
      B: 'Commerces',
      C: 'Enseignement',
      D: 'Santé et action sociale',
      E: 'Transports et déplacements',
      F: 'Sports, loisirs et culture',
      G: 'Tourisme'
    },
    label: 'Domaine d\'appartenance de l\'équipement'
  },
  {
    key: 'epci',
    'x-originalName': 'EPCI',
    type: 'string',
    'x-refersTo': 'http://rdf.insee.fr/def/geo#EtablissementPublicDeCooperationIntercommunale',
    title: 'Etablissement public de coopération intercommunal d\'implantation de l\'équipement',
    label: 'Etablissement public de coopération intercommunal d\'implantation de l\'équipement'
  },
  {
    key: 'dciris',
    'x-originalName': 'DCIRIS',
    type: 'string',
    title: 'Code IRIS d\'implantation de l\'équipement',
    'x-refersTo': 'http://rdf.insee.fr/def/geo#codeIRIS',
    label: 'Code IRIS d\'implantation de l\'équipement'
  },
  {
    key: 'lambert_x',
    'x-originalName': 'LAMBERT_X',
    type: 'number',
    title: 'Coordonnée X de l\'équipement',
    label: 'Coordonnée X de l\'équipement'
  },
  {
    key: 'lambert_y',
    'x-originalName': 'LAMBERT_Y',
    type: 'number',
    title: 'Coordonnée Y de l\'équipement',
    label: 'Coordonnée Y de l\'équipement'
  },
  {
    key: 'qp',
    'x-originalName': 'QP',
    type: 'string',
    title: 'Quartier prioritaire de la politique de la ville d\'appartenance de l\'équipement',
    label: 'Quartier prioritaire de la politique de la ville d\'appartenance de l\'équipement'
  },
  {
    key: 'quali_iris',
    'x-originalName': 'QUALI_IRIS',
    type: 'string',
    title: 'Indicateur de qualité du géoréférencement dans l\'iris',
    'x-labels': {
      1: 'Appartenance sûre au zonage',
      2: 'Appartenance probable au zonage',
      3: 'Appartenance aléatoire ou indéterminée au zonage',
      X: 'Non concerné par le zonage'
    },
    label: 'Indicateur de qualité du géoréférencement dans l\'iris'
  },
  {
    key: 'quali_qp',
    'x-originalName': 'QUALI_QP',
    type: 'string',
    title: 'Indicateur de qualité du géoréférencement dans le quartier prioritaire de la politique de la ville',
    'x-labels': {
      1: 'Appartenance sûre au zonage',
      2: 'Appartenance probable au zonage',
      3: 'Appartenance aléatoire ou indéterminée au zonage',
      X: 'Non concerné par le zonage'
    },
    label: 'Indicateur de qualité du géoréférencement dans le quartier prioritaire de la politique de la ville'
  },
  {
    key: 'quali_qva',
    'x-originalName': 'QUALI_QVA',
    type: 'string',
    title: 'Indicateur de qualité du géoréférencement dans le quartier de veille active',
    'x-labels': {
      1: 'Appartenance sûre au zonage',
      2: 'Appartenance probable au zonage',
      3: 'Appartenance aléatoire ou indéterminée au zonage',
      X: 'Non concerné par le zonage'
    },
    label: 'Indicateur de qualité du géoréférencement dans le quartier de veille active'
  },
  {
    key: 'quali_zfu',
    'x-originalName': 'QUALI_ZFU',
    type: 'string',
    title: 'Indicateur de qualité du géoréférencement dans la zone franche urbaine',
    'x-labels': {
      1: 'Appartenance sûre au zonage',
      2: 'Appartenance probable au zonage',
      3: 'Appartenance aléatoire ou indéterminée au zonage',
      X: 'Non concerné par le zonage'
    },
    label: 'Indicateur de qualité du géoréférencement dans la zone franche urbaine'
  },
  {
    key: 'quali_zus',
    'x-originalName': 'QUALI_ZUS',
    type: 'string',
    title: 'Indicateur de qualité du géoréférencement dans la zone urbaine sensible',
    'x-labels': {
      1: 'Appartenance sûre au zonage',
      2: 'Appartenance probable au zonage',
      3: 'Appartenance aléatoire ou indéterminée au zonage',
      X: 'Non concerné par le zonage'
    },
    label: 'Indicateur de qualité du géoréférencement dans la zone urbaine sensible'
  },
  {
    key: 'qualite_xy',
    'x-originalName': 'QUALITE_XY',
    type: 'string',
    title: 'Qualité d\'attribution des coordonnées XY pour un équipement',
    'x-labels': {
      Bonne: 'Bonne',
      Acceptable: 'Acceptable',
      'Non gĂŠolocalisĂŠ': 'Non-géolocalisé',
      Mauvaise: 'Mauvaise'
    },
    label: 'Qualité d\'attribution des coordonnées XY pour un équipement'
  },
  {
    key: 'qva',
    'x-originalName': 'QVA',
    type: 'string',
    title: 'Quartier de veille active d\'appartenance de l\'équipement',
    label: 'Quartier de veille active d\'appartenance de l\'équipement'
  },
  {
    key: 'reg',
    'x-originalName': 'REG',
    type: 'string',
    title: 'Région d\'implantation de l\'équipement',
    'x-labels': {
      11: 'Ile-de-France',
      24: 'Centre-Val de Loire',
      27: 'Bourgogne-Franche-Comté',
      28: 'Normandie',
      32: 'Hauts-de-France',
      44: 'Grand Est',
      52: 'Pays de la Loire',
      53: 'Bretagne',
      75: 'Nouvelle-Aquitaine',
      76: 'Occitanie',
      84: 'Auvergne-Rhône-Alpes',
      93: 'Provence-Alpes-Côte d\'Azur',
      94: 'Corse',
      '01': 'Guadeloupe',
      '02': 'Martinique',
      '03': 'Guyane',
      '04': 'La Réunion',
      '06': 'Mayotte'
    },
    label: 'Région d\'implantation de l\'équipement'
  },
  {
    key: 'sdom',
    'x-originalName': 'SDOM',
    type: 'string',
    title: 'Sous-domaine d\'appartenance de l\'équipement',
    'x-labels': {
      A1: 'Services publics',
      A2: 'Services généraux',
      A3: 'Services automobiles',
      A4: 'Artisanat du bâtiment',
      A5: 'Autres services à la population',
      B1: 'Grandes surfaces',
      B2: 'Commerces alimentaires',
      B3: 'Commerces spécialisés non-alimentaires',
      C1: 'Enseignement du premier degré',
      C2: 'Enseignement du second degré - premier cycle',
      C3: 'Enseignement du second degré - second cycle',
      C4: 'Enseignement supérieur non-universitaire',
      C5: 'Enseignement supérieur universitaire',
      C6: 'Formation continue',
      C7: 'Autres services de l\'éducation',
      D1: 'Etablissements et services de santé',
      D2: 'Fonctions médicales et paramédicales (à titre libéral)',
      D3: 'Autres établissements et services à caractère sanitaire',
      D4: 'Action sociale pour personnes âgées',
      D5: 'Action sociale pour enfants en bas-âge',
      D6: 'Action sociale pour handicapés',
      D7: 'Autres services d\'action sociale',
      E1: 'Infrastructures de transports',
      F1: 'Equipements sportifs',
      F2: 'Equipements de loisirs',
      F3: 'Equipements culturels et socioculturels',
      G1: 'Tourisme'
    },
    label: 'Sous-domaine d\'appartenance de l\'équipement'
  },
  {
    key: 'typequ',
    'x-originalName': 'TYPEQU',
    type: 'string',
    title: 'Type d\'équipement',
    'x-labels': {
      A101: 'POLICE',
      A104: 'GENDARMERIE',
      A105: 'COUR D\'APPEL (CA)',
      A108: 'CONSEIL DE PRUD\'HOMMES (CPH)',
      A109: 'TRIBUNAL DE COMMERCE (TCO)',
      A120: 'DRFIP (DIRECTION RÉGIONALE DES FINANCES PUBLIQUES)',
      A121: 'DDFIP (DIRECTION DÉPARTEMENTALE DES FINANCES PUBLIQUES)',
      A122: 'RÉSEAU DE PROXIMITÉ PÔLE EMPLOI',
      A124: 'MAISON DE JUSTICE ET DU DROIT',
      A125: 'ANTENNE DE JUSTICE',
      A126: 'CONSEIL DÉPARTEMENTAL D\'ACCÈS AU DROIT (CDAD)',
      A128: 'IMPLANTATIONS FRANCE SERVICES (IFS)',
      A129: 'MAIRIE',
      A130: 'BUREAU D\'AIDE JURIDICTIONNELLE (BAJ)',
      A131: 'TRIBUNAL JUDICIAIRE (TJ)',
      A132: 'TRIBUNAL DE PROXIMITÉ (TPRX)',
      A203: 'BANQUE, CAISSE D\'ÉPARGNE',
      A205: 'SERVICES FUNÉRAIRES',
      A206: 'BUREAU DE POSTE',
      A207: 'RELAIS POSTE',
      A208: 'AGENCE POSTALE',
      A301: 'RÉPARATION AUTOMOBILE ET DE MATÉRIEL AGRICOLE',
      A302: 'CONTRÔLE TECHNIQUE AUTOMOBILE',
      A303: 'LOCATION AUTO-UTILITAIRES LÉGERS',
      A304: 'ÉCOLE DE CONDUITE',
      A401: 'MAÇON',
      A402: 'PLÂTRIER PEINTRE',
      A403: 'MENUISIER CHARPENTIER SERRURIER',
      A404: 'PLOMBIER COUVREUR CHAUFFAGISTE',
      A405: 'ÉLECTRICIEN',
      A406: 'ENTREPRISE GÉNÉRALE DU BÂTIMENT',
      A501: 'COIFFURE',
      A502: 'VÉTÉRINAIRE',
      A503: 'AGENCE DE TRAVAIL TEMPORAIRE',
      A504: 'RESTAURANT- RESTAURATION RAPIDE',
      A505: 'AGENCE IMMOBILIÈRE',
      A506: 'PRESSING-LAVERIE AUTOMATIQUE',
      A507: 'INSTITUT DE BEAUTÉ-ONGLERIE',
      B101: 'HYPERMARCHÉ',
      B102: 'SUPERMARCHÉ',
      B103: 'GRANDE SURFACE DE BRICOLAGE',
      B201: 'SUPÉRETTE',
      B202: 'ÉPICERIE',
      B203: 'BOULANGERIE',
      B204: 'BOUCHERIE CHARCUTERIE',
      B205: 'PRODUITS SURGELÉS',
      B206: 'POISSONNERIE',
      B301: 'LIBRAIRIE, PAPETERIE, JOURNAUX',
      B302: 'MAGASIN DE VÊTEMENTS',
      B303: 'MAGASIN D\'ÉQUIPEMENTS DU FOYER',
      B304: 'MAGASIN DE CHAUSSURES',
      B305: 'MAGASIN D\'ÉLECTROMÉNAGER ET DE MAT. AUDIO-VIDEO',
      B306: 'MAGASIN DE MEUBLES',
      B307: 'MAGASIN D\'ARTICLES DE SPORTS ET DE LOISIRS',
      B308: 'MAGASIN DE REVÊTEMENTS MURS ET SOLS',
      B309: 'DROGUERIE QUINCAILLERIE BRICOLAGE',
      B310: 'PARFUMERIE-COSMÉTIQUE',
      B311: 'HORLOGERIE-BIJOUTERIE',
      B312: 'FLEURISTE-JARDINERIE-ANIMALERIE',
      B313: 'MAGASIN D\'OPTIQUE',
      B315: 'MAGASIN DE MATÉRIEL MÉDICAL ET ORTHOPÉDIQUE',
      B316: 'STATION-SERVICE',
      C101: 'ÉCOLE MATERNELLE',
      C102: 'ÉCOLE MATERNELLE DE REGROUPEMENT PÉDAGOGIQUE INTERCOMMUNAL (RPI) DISPERSÉ',
      C104: 'ÉCOLE ÉLÉMENTAIRE',
      C105: 'ÉCOLE ÉLÉMENTAIRE DE REGROUPEMENT PÉDAGOGIQUE INTERCOMMUNAL (RPI) DISPERSÉ',
      C201: 'COLLÈGE',
      C301: 'LYCÉE D\'ENSEIGNEMENT GÉNÉRAL ET/OU TECHNOLOGIQUE',
      C302: 'LYCÉE D\'ENSEIGNEMENT PROFESSIONNEl',
      C303: 'LYCÉE D\'ENSEIGNEMENT TECHNIQUE ET/OU PROFESSIONNEL AGRICOLE',
      C304: 'SGT SECTION D\'ENSEIGNEMENT GÉNÉRAL ET TECHNOLOGIQUE',
      C305: 'SEP SECTION D\'ENSEIGNEMENT PROFESSIONNEl',
      C401: 'STS SECTION TECHNICIEN SUPÉRIEUR, CPGE CLASSE PRÉPARATOIRE AUX GRANDES ÉCOLES',
      C402: 'FORMATION SANTÉ',
      C403: 'FORMATION COMMERCE',
      C409: 'AUTRE FORMATION POST BAC NON UNIVERSITAIRE',
      C501: 'UFR',
      C502: 'INSTITUT UNIVERSITAIRE',
      C503: 'ÉCOLE D\'INGÉNIEURS',
      C504: 'ENSEIGNEMENT GÉNÉRAL SUPÉRIEUR PRIVÉ',
      C505: 'ÉCOLE D\'ENSEIGNEMENT SUPÉRIEUR AGRICOLE',
      C509: 'AUTRE ENSEIGNEMENT SUPÉRIEUR',
      C601: 'CENTRE DE FORMATION D\'APPRENTIS HORS AGRICULTURE',
      C602: 'GRETA',
      C603: 'CENTRE DISPENSANT DE LA FORMATION CONTINUE AGRICOLE',
      C604: 'FORMATION AUX MÉTIERS DU SPORT',
      C605: 'CENTRE DISPENSANT DES FORMATIONS D\'APPRENTISSAGE AGRICOLE',
      C609: 'AUTRE FORMATION CONTINUE',
      C701: 'RÉSIDENCE UNIVERSITAIRE',
      C702: 'RESTAURANT UNIVERSITAIRE',
      D101: 'ÉTABLISSEMENT SANTÉ COURT SÉJOUR',
      D102: 'ÉTABLISSEMENT SANTÉ MOYEN SÉJOUR',
      D103: 'ÉTABLISSEMENT SANTÉ LONG SÉJOUR',
      D104: 'ÉTABLISSEMENT PSYCHIATRIQUE',
      D105: 'CENTRE LUTTE CANCER',
      D106: 'URGENCES',
      D107: 'MATERNITÉ',
      D108: 'CENTRE DE SANTÉ',
      D109: 'STRUCTURE PSYCHIATRIQUE EN AMBULATOIRE',
      D110: 'CENTRE MÉDECINE PRÉVENTIVE',
      D111: 'DIALYSE',
      D112: 'HOSPITALISATION À DOMICILE',
      D113: 'MAISON DE SANTÉ PLURIDISCIPLINAIRE',
      D201: 'MÉDECIN GÉNÉRALISTE',
      D202: 'SPÉCIALISTE EN CARDIOLOGIE',
      D203: 'SPÉCIALISTE EN DERMATOLOGIE VÉNÉRÉOLOGIE',
      D206: 'SPÉCIALISTE EN GASTRO-ENTÉROLOGIE HÉPATOLOGIE',
      D207: 'SPÉCIALISTE EN PSYCHIATRIE',
      D208: 'SPÉCIALISTE EN OPHTALMOLOGIE',
      D209: 'SPÉCIALISTE EN OTO-RHINO-LARYNGOLOGIE',
      D210: 'SPÉCIALISTE EN PÉDIATRIE',
      D211: 'SPÉCIALISTE EN PNEUMOLOGIE',
      D212: 'SPÉCIALISTE EN RADIODIAGNOSTIC ET IMAGERIE MÉDICALE',
      D213: 'SPÉCIALISTE EN STOMATOLOGIE',
      D214: 'SPÉCIALISTE EN GYNÉCOLOGIE (MÉDICALE ET/OU OBSTÉTRIQUE)',
      D221: 'CHIRURGIEN DENTISTE',
      D231: 'SAGE-FEMME',
      D232: 'INFIRMIER',
      D233: 'MASSEUR KINÉSITHÉRAPEUTE',
      D235: 'ORTHOPHONISTE',
      D236: 'ORTHOPTISTE',
      D237: 'PÉDICURE-PODOLOGUE',
      D238: 'AUDIO PROTHÉSISTE',
      D239: 'ERGOTHÉRAPEUTE',
      D240: 'PSYCHOMOTRICIEN',
      D242: 'DIÉTÉTICIEN',
      D243: 'PSYCHOLOGUE',
      D302: 'LABORATOIRE D ANALYSES ET DE BIOLOGIE MÉDICALE',
      D303: 'AMBULANCE',
      D304: 'TRANSFUSION SANGUINE',
      D305: 'ÉTABLISSEMENT THERMAl',
      D307: 'PHARMACIE',
      D401: 'PERSONNES ÂGÉES : HÉBERGEMENT',
      D402: 'PERSONNES ÂGÉES : SOINS À DOMICILE',
      D403: 'PERSONNES ÂGÉES : SERVICES D\'AIDE',
      D502: 'ÉTABLISSEMENT D\'ACCUEIL DU JEUNE ENFANT (EAJE)',
      D601: 'ENFANTS HANDICAPÉS : HÉBERGEMENT',
      D602: 'ENFANTS HANDICAPÉS : SERVICES À DOMICILE OU AMBULATOIRES',
      D603: 'ADULTES HANDICAPÉS : ACCUEIL/HÉBERGEMENT',
      D604: 'ADULTES HANDICAPÉS : SERVICES D\'AIDE',
      D605: 'TRAVAIL PROTÉGÉ',
      D606: 'ADULTES HANDICAPÉS : SERVICES DE SOINS À DOMICILE',
      D701: 'PROTECTION DE L\'ENFANCE - HÉBERGEMENT',
      D702: 'PROTECTION DE L\'ENFANCE - ACTION ÉDUCATIVE',
      D703: 'CHRS : CENTRE D\'HÉBERGEMENT ET DE RÉINSERTION SOCIALE',
      D704: 'CENTRE PROVISOIRE D\'HÉBERGEMENT',
      D705: 'CENTRE ACCUEIL DEMANDEUR D\'ASILE',
      D709: 'AUTRES ÉTABLISSEMENTS POUR ADULTES ET FAMILLES EN DIFFICULTÉ',
      E101: 'TAXI-VTC',
      E102: 'AÉROPORT',
      E107: 'GARE DE VOYAGEURS D\'INTÉRÊT NATIONAl',
      E108: 'GARE DE VOYAGEURS D\'INTÉRÊT RÉGIONAl',
      E109: 'GARE DE VOYAGEURS D\'INTÉRÊT LOCAl',
      F101: 'BASSIN DE NATATION',
      F102: 'BOULODROME',
      F103: 'TENNIS',
      F104: 'ÉQUIPEMENT DE CYCLISME',
      F105: 'DOMAINE SKIABLE',
      F106: 'CENTRE ÉQUESTRE',
      F107: 'ATHLÉTISME',
      F108: 'TERRAIN DE GOLF',
      F109: 'PARCOURS SPORTIF/SANTÉ',
      F110: 'SPORTS DE GLACE',
      F111: 'PLATEAUX ET TERRAINS DE JEUX EXTÉRIEURS',
      F112: 'SALLES SPÉCIALISÉES',
      F113: 'TERRAINS DE GRANDS JEUX',
      F114: 'SALLES DE COMBAT',
      F116: 'SALLES NON SPÉCIALISÉES',
      F117: 'ROLLER-SKATE-VÉLO BICROSS OU FREESTYLE',
      F118: 'SPORTS NAUTIQUES',
      F119: 'BOWLING',
      F120: 'SALLES DE REMISE EN FORME',
      F121: 'SALLES MULTISPORTS (GYMNASES)',
      F201: 'BAIGNADE AMENAGÉE',
      F202: 'PORT DE PLAISANCE – MOUILLAGE',
      F203: 'BOUCLE DE RANDONNÉE',
      F303: 'CINÉMA',
      F305: 'CONSERVATOIRE',
      F307: 'BIBLIOTHÈQUE',
      F311: 'LIVRES ET PRESSE',
      F312: 'EXPOSITION ET MEDIATION CULTURELLE',
      F313: 'ESPACE REMARQUABLE ET PATRIMOINE',
      F314: 'ARCHIVES',
      F315: 'ARTS DU SPECTACLE',
      G101: 'AGENCE DE VOYAGE',
      G102: 'HÔTEl',
      G103: 'CAMPING',
      G104: 'INFORMATION TOURISTIQUE'
    },
    label: 'Type d\'équipement'
  },
  {
    key: 'uu2020',
    'x-originalName': 'UU2020',
    type: 'string',
    title: 'Unité urbaine 2020 d\'implantation de l\'équipement',
    label: 'Unité urbaine 2020 d\'implantation de l\'équipement'
  },
  {
    key: 'zfu',
    'x-originalName': 'ZFU',
    type: 'string',
    title: 'Zone franche urbaine d\'appartenance de l\'équipement',
    label: 'Zone franche urbaine d\'appartenance de l\'équipement'
  },
  {
    key: 'zus',
    'x-originalName': 'ZUS',
    type: 'string',
    title: 'Zone urbaine sensible d\'appartenance de l\'équipement',
    label: 'Zone urbaine sensible d\'appartenance de l\'équipement'
  },
  {
    key: 'latitude',
    type: 'number',
    'x-refersTo': 'http://schema.org/latitude',
    label: 'LATITUDE'
  },
  {
    key: 'longitude',
    type: 'number',
    'x-refersTo': 'http://schema.org/longitude',
    label: 'LONGITUDE'
  }
]
