module.exports = [
  {
    key: 'civilite',
    'x-originalName': 'civilité',
    type: 'string',
    'x-labels': {
      H: 'Homme',
      F: 'Femme'
    },
    title: 'Civilité'
  },
  {
    key: 'nom',
    'x-originalName': 'nom',
    type: 'string',
    title: 'Nom'
  },
  {
    key: 'prenom',
    'x-originalName': 'prénom',
    type: 'string',
    title: 'Prénom'
  },
  {
    key: 'libelle',
    'x-originalName': 'libellé',
    type: 'string',
    'x-refersTo': 'http://www.w3.org/2000/01/rdf-schema#title',
    'x-concept': {
      id: 'title',
      title: 'Libellé',
      primary: true
    },
    title: 'Libellé'
  },
  {
    key: 'etablissement',
    'x-originalName': 'etablissement',
    type: 'string',
    title: 'Etablissement'
  },
  {
    key: 'adresse',
    'x-originalName': 'adresse',
    type: 'string',
    'x-refersTo': 'http://schema.org/address',
    'x-concept': {
      id: 'address',
      title: 'Adresse',
      primary: true
    },
    title: 'Adresse'
  },
  {
    key: 'complement_adresse',
    'x-originalName': 'complément adresse',
    type: 'string',
    title: 'Complément d\'adresse'
  },
  {
    key: 'code_postal',
    'x-originalName': 'code postal',
    type: 'string',
    'x-refersTo': 'http://schema.org/postalCode',
    'x-concept': {
      id: 'postalCode',
      title: 'Code postal',
      primary: true
    },
    title: 'Code postal'
  },
  {
    key: 'commune',
    'x-originalName': 'commune',
    type: 'string',
    'x-refersTo': 'http://schema.org/City',
    'x-concept': {
      id: 'city',
      title: 'Commune',
      primary: true
    },
    title: 'Commune'
  },
  {
    key: 'telephone',
    'x-originalName': 'téléphone',
    type: 'string',
    'x-refersTo': 'https://www.w3.org/2006/vcard/ns#tel',
    'x-concept': {
      id: 'tel',
      title: 'N° de téléphone',
      primary: true
    },
    title: 'Téléphone'
  },
  {
    key: 'profession',
    'x-originalName': 'profession',
    type: 'string',
    title: 'Profession',
    'x-labels': {
      1: 'Ambulance / Véhicule sanitaire léger',
      2: 'Anatomo-Cyto-Pathologiste',
      3: 'Anesthésiste réanimateur',
      4: 'Cancérologue radiothérapeute',
      5: 'Cancérologue médical',
      6: 'Cardiologue',
      7: 'Chirurgien général',
      8: 'Chirurgien infantile',
      9: 'Chirurgien maxillo-facial',
      10: 'Chirurgien maxillo-facial et stomatologiste',
      11: 'Chirurgien oral',
      12: 'Chirurgien orthopédiste et traumatologue',
      13: 'Chirurgien plasticien',
      14: 'Chirurgien thoracique et cardio-vasculaire',
      15: 'Chirurgien urologue',
      16: 'Chirurgien vasculaire',
      17: 'Chirurgien viscéral',
      18: 'Chirurgien-dentiste',
      19: 'Chirurgien-dentiste spécialiste en orthopédie dento-faciale',
      20: 'Chirurgiens-dentistes spécialiste en chirurgie orale',
      21: 'Chirurgiens-dentistes spécialiste en médecine bucco-dentaire',
      22: 'Dermatologue et vénérologue',
      23: 'Endocrinologue-diabétologue',
      24: 'Fournisseur de matériel médical et para-médical',
      25: 'Fournisseur de matériel médical et para-médical',
      26: 'Fournisseur de matériel médical et para-médical',
      27: 'Fournisseur de matériel médical et para-médical',
      28: 'Fournisseur de matériel médical et para-médical',
      29: 'Fournisseur de matériel médical et para-médical',
      30: 'Fournisseur de matériel médical et para-médical',
      31: 'Fournisseur de matériel médical et para-médical',
      32: 'Fournisseur de matériel médical et para-médical ',
      33: 'Gastro-entérologue et hépatologue',
      34: 'Gériatre',
      35: 'Gynécologue médical',
      36: 'Gynécologue médical et obstétricien',
      37: 'Gynécologue obstétricien',
      38: 'Hématologue',
      39: 'Infirmier',
      40: 'Laboratoire',
      41: 'Laboratoire',
      42: 'Laboratoire d\'anatomo-pathologie',
      43: 'Masseur-kinésithérapeute',
      44: 'Médecin biologiste',
      45: 'Médecin généraliste',
      46: 'Médecin généraliste',
      47: 'Médecin généraliste',
      48: 'Médecin généticien',
      49: 'Médecin spécialiste en médecine nucléaire',
      50: 'Médecin spécialiste en santé publique et médecine sociale',
      51: 'Néphrologue',
      52: 'Neurochirurgien',
      53: 'Neurologue',
      54: 'Neuropsychiatre',
      55: 'Obstétricien',
      56: 'Ophtalmologiste',
      57: 'Orthophoniste',
      58: 'Orthoptiste',
      59: 'Oto-Rhino-Laryngologue (ORL) et chirurgien cervico-facial',
      60: 'Pédiatre',
      61: 'Pédicure-podologue',
      62: 'Pharmacien',
      63: 'Pharmacien',
      64: 'Pneumologue',
      65: 'Psychiatre',
      66: 'Psychiatre de l\'enfant et de l\'adolescent',
      67: 'Radiologue',
      68: 'Radiothérapeute',
      69: 'Réanimateur médical',
      70: 'Rhumatologue',
      71: 'Sage-femme',
      72: 'Spécialiste en médecine interne',
      73: 'Spécialiste en médecine physique et de réadaptation',
      74: 'Stomatologiste'
    }
  },
  {
    key: 'mode_dexercice_particulier',
    'x-originalName': 'mode d’exercice particulier',
    type: 'string',
    title: 'Mode d’exercice particulier',
    'x-labels': {
      1: 'Acupuncteur',
      2: 'Allergologue',
      3: 'Angiologue',
      4: 'Echographiste',
      5: 'Homéopathe',
      6: 'Médecin thermaliste',
      7: 'Médecine appliquée aux sports',
      8: 'Phoniatre'
    }
  },
  {
    key: 'nature_dexercice',
    'x-originalName': 'nature d’exercice',
    type: 'string',
    title: 'Nature d’exercice',
    'x-labels': {
      1: 'N\'exerce pas actuellement',
      2: 'Libéral activité salariée',
      3: 'Libéral intégral',
      4: 'Libéral temps partiel hospitalier',
      5: 'Libéral temps plein hospitalier',
      6: 'Pharmacie mutualiste',
      7: 'T. plein hosp. contrat mixte',
      8: 'T. plein hosp./mal. aut. med.'
    }
  },
  {
    key: 'convention',
    'x-originalName': 'convention',
    type: 'string',
    title: 'Convention',
    'x-labels': {
      nc: 'Non conventionné',
      c1: 'Secteur 1 ou conventionné',
      c2: 'Secteur 1 ou conventionné avec droit au dépassement permanent',
      c3: 'Secteur 2'
    }
  },
  {
    key: 'option_contrat_dacces_aux_soins',
    'x-originalName': 'option contrat d’accès aux soins',
    type: 'string',
    title: 'Option contrat d’accès aux soins'
  },
  {
    key: 'sesam_vitale',
    'x-originalName': 'Sesam Vitale',
    type: 'string',
    title: 'Sesam Vitale'
  },
  {
    key: 'code_ccam_de_lacte',
    'x-originalName': 'Code CCAM de l’acte',
    type: 'string',
    description: 'Code de la consultation et éventuellement de la majoration',
    title: 'Code CCAM de l’acte'
  },
  {
    key: 'famille_dacte',
    'x-originalName': 'Famille d’acte',
    type: 'string',
    title: 'Famille d’acte',
    'x-labels': {
      1: 'Ablation chirurgicale de lésion de la peau ou du tissu sous-cutanée sauf infection, collection et ulcère',
      2: 'Ablation chirurgicale de lésion infectieuse, de collection (abcès…) ou d\'ulcère de la peau ou du tissu sous-cutanée',
      3: 'Ablation de bouchon de cérumen ou de corps étranger du conduit auditif (oreille)',
      4: 'Ablation de lésion du pavillon de l\'oreille',
      5: 'Ablation de matériel d\'ostéosynthèse (broche, plaque, vis) sur un os de membre',
      6: 'Accouchements par voie naturelle ou par césarienne',
      7: 'Acte préprothétique',
      8: 'Actes médicaux de confection de plâtre (en dehors des fractures), de contention souple et d\'attelle de posture, de membre',
      9: 'Actes médicaux de confection d\'orthèse de membre',
      10: 'Actes médicaux et chirurgicaux sur le nez ou les cavités nasales ',
      11: 'Actes médicaux et chirurgicaux sur le tympan (otites, ablation de corps étranger de la caisse du tympan…)',
      12: 'Actes médicaux et chirurgicaux sur l\'utérus',
      13: 'Actes médicaux sur les articulations pour évacuation et infiltration d\'épanchement articulaire de membre (y compris synoviorthèse)',
      14: 'Actes médicaux sur les sinus',
      15: 'Actes pour assistance médicale à la procréation (insémination artificielle et fécondation in vitro)',
      16: 'Adaptation de lentilles cornéennes thérapeutiques',
      17: 'Amniocentèse et biopsie du placenta',
      18: 'Biopsie de l\'appareil urinaire',
      19: 'Biopsie de peau et d\'ongle',
      20: 'Biopsies de prostate',
      21: 'Chirurgie (ablation et reconstruction) du sein - hors esthétique',
      22: 'Chirurgie de cholestéatome (oreille)',
      23: 'Chirurgie de décompression de la moelle épinière',
      24: 'Chirurgie de la cataracte (du cristallin)',
      25: 'Chirurgie de la cavité abdominale et du petit bassin',
      26: 'Chirurgie de la cavité buccale',
      27: 'Chirurgie de la paupière et du sourcil',
      28: 'Chirurgie de la prostate',
      29: 'Chirurgie de la rétine',
      30: 'Chirurgie de la surdité (hors implants cochléaires)',
      31: 'Chirurgie de la thyroïde et des parathyroïdes',
      32: 'Chirurgie de la vésicule et des voies biliaires',
      33: 'Chirurgie de la vessie',
      34: 'Chirurgie de l\'anus (hors hémorroïdes)',
      35: 'Chirurgie de l\'appendice (appendicite)',
      36: 'Chirurgie de l\'arrière-gorge (oropharynx) et du pharynx',
      37: 'Chirurgie de l\'articulation de la hanche (hors fracture - luxation)',
      38: 'Chirurgie de l\'articulation du genou (hors fracture - luxation)',
      39: 'Chirurgie de l\'estomac hors chirurgie de l\'obésité',
      40: 'Chirurgie de l\'intestin grêle',
      41: 'Chirurgie de l\'ongle',
      42: 'Chirurgie de l\'uretère (voies urinaires entre le rein et la vessie)',
      43: 'Chirurgie de l\'urètre (voie urinaire entre la vessie et l\'extérieur)',
      44: 'Chirurgie de malformation du cœur',
      45: 'Chirurgie de soutènement de la vessie (incontinence urinaire)',
      46: 'Chirurgie dentaire',
      47: 'Chirurgie des amygdales et végétations',
      48: 'Chirurgie des artères du cou (carotides)',
      49: 'Chirurgie des articulations de la cheville et du pied (hors fracture - luxation)',
      50: 'Chirurgie des articulations du coude, du poignet ou de la main (hors fracture - luxation)',
      51: 'Chirurgie des déformations de la colonne vertébrale',
      52: 'Chirurgie des glandes salivaires',
      53: 'Chirurgie des hernies discales (colonne vertébrale)',
      54: 'Chirurgie des hernies ou des éventrations de la paroi abdominale',
      55: 'Chirurgie des lèvres',
      56: 'Chirurgie des oreilles décollées',
      57: 'Chirurgie des organes génitaux féminins hors ovaire et utérus',
      58: 'Chirurgie des organes génitaux masculins (hors pénis et prostate)',
      59: 'Chirurgie des os de la face (hors fracture - luxation)',
      60: 'Chirurgie des os et de l\'articulation de l\'épaule (hors fracture - luxation)',
      61: 'Chirurgie des ovaires et des trompes',
      62: 'Chirurgie des poumons, de la plèvre ou du médiastin',
      63: 'Chirurgie des reins',
      64: 'Chirurgie des sinus',
      65: 'Chirurgie des tendons, des muscles ou des parties molles du membre inférieur',
      66: 'Chirurgie des tendons, muscles, parties molles du membre supérieur',
      67: 'Chirurgie des valves du cœur',
      68: 'Chirurgie des varices du membre inférieur',
      69: 'Chirurgie du cerveau',
      70: 'Chirurgie du côlon (gros intestin)',
      71: 'Chirurgie du foie',
      72: 'Chirurgie du larynx',
      73: 'Chirurgie du pancréas',
      74: 'Chirurgie du pénis',
      75: 'Chirurgie du rectum',
      76: 'Chirurgie du strabisme',
      77: 'Chirurgie du vagin et des organes génitaux externes féminins pour correction des ambiguïtés sexuelles',
      78: 'Chirurgie et désobstruction d\'accès vasculaire pour hémodialyse (dialyse pour insuffisance rénale chronique)',
      79: 'Chirurgie osseuse du membre inférieur (hors fracture - luxation)',
      80: 'Chirurgie pour obésité',
      81: 'Colposcopie et endoscopie de l\'appareil génital féminin',
      82: 'Décompression chirurgicale de nerf du membre supérieur',
      83: 'Destruction de la thyroïde par iode radioactif',
      84: 'Destruction de lésion cutanée du périnée',
      85: 'Destruction de lésion superficielle de la peau',
      86: 'Destruction de tumeur du foie par radiofréquence',
      87: 'Dévitalisation de dent',
      88: 'Dialyse péritonéale (insuffisance rénale chronique)',
      89: 'Dialyse rénale par voie vasculaire (hémodialyse pour insuffisance rénale chronique)',
      90: 'Dilatation des artères du cœur avec ou sans pose d\'endoprothèse (stent)',
      91: 'Echodoppler cardiaque d\'effort et électrocardiogramme (ECG) d\'effort',
      92: 'Echodoppler des artères (hors artères intrathoraciques)',
      93: 'Echodoppler des veines',
      94: 'Echodoppler du cœur et des artères intrathoraciques',
      95: 'Echoendoscopie de l\'appareil digestif',
      96: 'Échographie d\'articulation, de muscle, de tendon ou de peau',
      97: 'Échographie de la grossesse et pelvimétrie',
      98: 'Échographie de la thyroïde et des parathyroïdes',
      99: 'Échographie de l\'appareil digestif',
      100: 'Échographie de l\'appareil urinaire, de l\'appareil génital et du petit bassin',
      101: 'Échographie du sein',
      102: 'Échographie du système nerveux',
      103: 'Électrocardiogramme (ECG)',
      104: 'Électrochoc',
      105: 'Electroencéphalogramme (EEG)',
      106: 'Electromyogramme (EMG)',
      107: 'Electromyogramme (EMG) du périnée ',
      108: 'Endoscopie de la trachée et des bronches',
      109: 'Endoscopie de l\'appareil urinaire',
      110: 'Endoscopie des voies aériennes supérieures (nez, sinus, pharynx, larynx)',
      111: 'Endoscopie et traitement endoscopique de l\'œsophage, l\'estomac, le duodénum ou des voies biliaires',
      112: 'Endoscopie et traitement endoscopique du côlon (gros intestin)',
      113: 'Examen de la peau au dermatoscope (loupe)',
      114: 'Examen de la vision',
      115: 'Exploration de la voix et de la parole',
      116: 'Exploration de l\'appareil circulatoire périphérique',
      117: 'Exploration de l\'audition, de l\'équilibre et des vertiges',
      118: 'Exploration du cœur (mesure des pressions et débit du cœur)',
      119: 'Exploration du rythme cardiaque',
      120: 'Exploration du sommeil',
      121: 'Exploration du tube digestif - hors imagerie et endoscopie',
      122: 'Exploration endoscopique ou par vidéocapsule de l\'intestin grêle',
      123: 'Exploration fonctionnelle de la marche',
      124: 'Exploration fonctionnelle de la respiration (EFR)',
      125: 'Exploration fonctionnelle de l\'appareil urinaire',
      126: 'Exploration neurologique de l\'œil',
      127: 'Exploration sensorielle et motrice: \'Potentiels évoqués (sauf visuels et auditifs)',
      128: 'Extraction de dents',
      129: 'Fixation chirurgicale de vertèbres entre elles hors déformations de la colonne vertébrale',
      130: 'Fixation du vagin (prolapsus...)',
      131: 'Imagerie de l\'œil (échographie, angiographie…)',
      132: 'Infiltration de médicament anesthésique des nerfs de la colonne vertébrale et des troncs nerveux pour exploration de la douleur',
      133: 'Infiltration de médicament autour de nerf de colonne vertébrale pour traitement de la douleur',
      134: 'Infiltration de médicament de nerf des membres',
      135: 'Infiltration de médicament ou destruction d\'articulation postérieure de la colonne vertébrale',
      136: 'Injection de médicament en péridural pour exploration ou traitement de la douleur',
      137: 'Injection de toxine botulique (paupières, face et membres) - hors esthétique',
      138: 'Instillation de médicament dans la vessie',
      139: 'Interruption thérapeutique de grossesse (hors Interruption volontaire - IVG)',
      140: 'IRM des membres ou de la colonne vertébrale',
      141: 'IRM des vaisseaux ou du cœur',
      142: 'IRM du crâne, de la face ou du cou',
      143: 'IRM du sein',
      144: 'IRM du thorax ou de l\'abdomen',
      145: 'Ostéodensitométrie (ostéoporose)',
      146: 'Ostéosynthèse (broche, plaque, vis) pour fracture de membre supérieur',
      147: 'Parodontologie',
      148: 'Ponction d\'ascite (liquide dans la cavité abdominale)',
      149: 'Ponction et biopsie d\'articulation ou d\'os de membre ou du bassin',
      150: 'Ponction et biopsie de la thyroïde',
      151: 'Ponction et biopsie de l\'appareil génital féminin',
      152: 'Ponction et biopsie de moelle osseuse et d\'os',
      153: 'Ponction et biopsie du foie et de l\'appareil digestif',
      154: 'Ponction et biopsie du système nerveux (cerveau)',
      155: 'Ponction, biopsie et macrobiopsie du sein',
      156: 'Pontage des artères du cœur (coronaires)',
      157: 'Pose de prothèse amovible (appareil dentaire)',
      158: 'Pose de prothèse fixée (couronne, bridge)',
      159: 'Pose de repère dans le sein',
      160: 'Pose de sonde ou d\'endoprothèse des voies urinaires',
      161: 'Pose d\'un système diffuseur pour chimiothérapie',
      162: 'Pose, ablation ou changement de stérilet ou d\'implant contraceptif souscutanée',
      163: 'Prévention dentaire chez l\'enfant',
      164: 'Prévention et hygiène dentaire',
      165: 'Radiographie de l\'abdomen',
      166: 'Radiographie dentaire',
      167: 'Radiographie dentaire',
      168: 'Radiographie des artères (artériographies) sauf artères du cœur',
      169: 'Radiographie des artères du cœur (artères coronaires)',
      170: 'Radiographie des reins, des voies urinaires ou de l\'utérus',
      171: 'Radiographie des veines (phlébographies)',
      172: 'Radiographie du poumon et du thorax',
      173: 'Radiographie du sein (mammographie...)',
      174: 'Radiographie osseuse et articulaire de la colonne vertébrale et radiographie de la moelle épinière',
      175: 'Radiographie osseuse et articulaire du crâne et de la face et radiographie des tissus mous du cou',
      176: 'Radiographie osseuse et articulaire du membre inférieur',
      177: 'Radiographie osseuse et articulaire du membre supérieur',
      178: 'Radiographie spécifique de l\'enfant',
      179: 'Rééducation cardiaque',
      180: 'Rééducation de l\'incontinence anale ou rééducation vésicale',
      181: 'Rééducation des vertiges et de l\'équilibre',
      182: 'Réparation de la peau par greffe ou lambeau',
      183: 'Réparation de prothèse amovible (appareil dentaire)',
      184: 'Réparation ou reconstruction de l\'oreille et du conduit auditif',
      185: 'Scanner des membres ou de la colonne vertébrale',
      186: 'Scanner des vaisseaux ou du cœur',
      187: 'Scanner du crâne, de la face ou du cou',
      188: 'Scanner du thorax, du sein ou de l\'abdomen',
      189: 'Scintigraphie - hors cœur, thyroïde, poumon et os',
      190: 'Scintigraphie de la thyroïde',
      191: 'Scintigraphie du cœur et des vaisseaux',
      192: 'Scintigraphie osseuse et musculaire',
      193: 'Scintigraphie pulmonaire',
      194: 'Séance d\'acupuncture',
      195: 'Séance de compression pour œdème postchirurgical de membre',
      196: 'Séance de désensibilisation',
      197: 'Séance de sclérose ou d\'exérèse de varice du membre inférieur',
      198: 'Séance de traitement de lésions de la peau par ultraviolets (UV) - hors esthétique',
      199: 'Séance d\'élongation et de manipulation de la colonne vertébrale',
      200: 'Test d\'allergologie',
      201: 'Test d\'évaluation neuropsychologique ',
      202: 'Tomoscintigraphie (TEP)',
      203: 'Traitement de la conjonctive (œil)',
      204: 'Traitement de la cornée (œil)',
      205: 'Traitement de lésion de veine du membre supérieur (hors varices)',
      206: 'Traitement de lésion des artères de l\'abdomen et du petit bassin',
      207: 'Traitement de lésion des artères du membre inférieur',
      208: 'Traitement de l\'iris et du segment antérieur de l\'œil (glaucome…)',
      209: 'Traitement de varices œsophagiennes',
      210: 'Traitement des calculs du rein et des voies urinaires',
      211: 'Traitement des caries',
      212: 'Traitement des caries/fractures',
      213: 'Traitement des fractures des os de la face',
      214: 'Traitement des hémorroïdes',
      215: 'Traitement des troubles du rythme du cœur',
      216: 'Traitement des voies lacrymales',
      217: 'Traitement orthopédique de fracture ou de luxation de membre inférieur',
      218: 'Traitement orthopédique de fracture ou de luxation de membre supérieur',
      219: 'Traitement par laser de la rétine et photothérapie',
      220: 'Traitement par ostéosynthèse (broche, plaque, vis…) des fractures du membre inférieur'
    }
  },
  {
    key: 'montant_activite_principale',
    'x-originalName': 'Montant activité principale',
    type: 'number',
    description: 'Montant généralement constaté pour l’activité principale',
    title: 'Montant activité principale'
  },
  {
    key: 'borne_inf_activite_principale',
    'x-originalName': 'Borne inf activité principale',
    type: 'number',
    description: 'Borne inférieure du montant de l’activité principale',
    title: 'Borne inf activité principale'
  },
  {
    key: 'borne_sup_activite_principale',
    'x-originalName': 'Borne sup activité principale',
    type: 'number',
    description: 'Borne supérieure du montant de l’activité principale',
    title: 'Borne sup activité principale'
  },
  {
    key: 'montant_activite_2e_interv',
    'x-originalName': 'Montant activité 2e interv',
    type: 'number',
    description: 'Montant généralement constaté pour l’activité du 2nd intervenant',
    title: 'Montant activité 2e interv'
  },
  {
    key: 'borne_inf_activite_2e_interv',
    'x-originalName': 'Borne inf activité 2e interv',
    type: 'number',
    description: 'Borne inférieure du montant de l’activité 2nd intervenant',
    title: 'Borne inf activité 2e interv'
  },
  {
    key: 'borne_sup_activite_2e_interv',
    'x-originalName': 'Borne sup activité 2e interv',
    type: 'number',
    description: 'Borne supérieure du montant de l’activité 2nd intervenant',
    title: 'Borne sup activité 2e interv'
  },
  {
    key: 'montant_activite_imagerie',
    'x-originalName': 'Montant activité imagerie',
    type: 'number',
    description: 'Montant généralement constaté pour l’activité d’imagerie',
    title: 'Montant activité imagerie'
  },
  {
    key: 'borne_inf_activite_imagerie',
    'x-originalName': 'Borne inf activité imagerie',
    type: 'number',
    description: 'Borne inférieure du montant de l’activité d’imagerie',
    title: 'Borne inf activité imagerie'
  },
  {
    key: 'borne_sup_activite_imagerie',
    'x-originalName': 'Borne sup activité imagerie',
    type: 'number',
    description: 'Borne supérieure du montant de l’activité d’imagerie',
    title: 'Borne sup activité imagerie'
  },
  {
    key: 'montant_activite_anesthesie',
    'x-originalName': 'Montant activité anesthésie',
    type: 'number',
    description: 'Montant généralement constaté pour l’activité d’anesthésie',
    title: 'Montant activité anesthésie'
  },
  {
    key: 'borne_inf_activite_anesthesie',
    'x-originalName': 'Borne inf activité anesthésie',
    type: 'number',
    description: 'Borne inférieure du montant de l’activité d’anesthésie',
    title: 'Borne inf activité anesthésie'
  },
  {
    key: 'borne_sup_activite_anesthesie',
    'x-originalName': 'Borne sup activité anesthésie',
    type: 'number',
    description: 'Borne supérieure du montant de l’activité d’anesthésie',
    title: 'Borne sup activité anesthésie'
  },
  {
    key: 'montant_activite_extracorp',
    'x-originalName': 'Montant activité extra-corp',
    type: 'number',
    description: 'Montant généralement constaté pour l’activité de circulation extra-corporelle',
    title: 'Montant activité extra-corp'
  },
  {
    key: 'borne_inf_activite_extracorp',
    'x-originalName': 'Borne inf activité extra-corp',
    type: 'number',
    description: 'Borne inférieure du montant de l’activité de circulation extra-corporelle',
    title: 'Borne inf activité extra-corp'
  },
  {
    key: 'borne_sup_activite_extracorpo',
    'x-originalName': 'Borne sup activité extra-corpo',
    type: 'number',
    description: 'Borne supérieure du montant de l’activité de circulation extra-corporelle',
    title: 'Borne sup activité extra-corpo'
  },
  {
    key: 'identifiant',
    'x-originalName': 'Identifiant',
    type: 'string',
    title: 'Identifiant'
  }
]
